# Generated by Django 4.1.3 on 2024-12-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickfinance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=500),
        ),
    ]
