# Generated by Django 4.1.3 on 2024-12-12 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickfinance', '0002_alter_answer_answer_alter_question_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='types',
            old_name='gfg_name',
            new_name='skill',
        ),
        migrations.RemoveField(
            model_name='question',
            name='gfg',
        ),
        migrations.AddField(
            model_name='question',
            name='skill',
            field=models.ForeignKey(default=str, on_delete=django.db.models.deletion.CASCADE, to='quickfinance.types'),
            preserve_default=False,
        ),
    ]
