# Generated by Django 4.1.3 on 2024-12-12 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickfinance', '0003_rename_gfg_name_types_skill_remove_question_gfg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='skill',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Types',
        ),
    ]
